site_name: INGenious Playwright Studio
theme:
 name: material
 favicon: doc_images/favicon.ico
 features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
 logo: img/logo/SmallLogoWhite.png 
 custom_dir: overrides
 user_color_mode_toggle: true
 #palette: 

    # Palette toggle for light mode
    #- scheme: default
    #  toggle:
    #    icon: material/brightness-7 
    #    name: Switch to dark mode

    # Palette toggle for dark mode
    #- scheme: slate
    #  toggle:
    #    icon: material/brightness-4
    #    name: Switch to light mode

 icon:
  admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: material/lightning-bolt
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  
  repo: simple/github

plugins:
    - search

nav:
 - Home:
    - Premise : index.md
    - Getting Started: gettingstarted.md
    - Know the framework: knowyourframework.md
 - Browser Testing: 
    - Create Your First Browser Test: browsertesting/index.md
    - Locator Strategies: browsertesting/playwrightlocatorstrategy.md
    - Auto-waiting: browsertesting/autowaiting.md
    - Actions: 
        - Browser/Page: playwrightActions/browser.md
        - Click: playwrightActions/clicks.md
        - Text: playwrightActions/textinput.md
        - Dropdown: playwrightActions/dropdowns.md
        - Data Storage: playwrightActions/store.md
        - Focus: playwrightActions/focus.md
        - JavaScript: playwrightActions/js.md
        - Keyboard: playwrightActions/keyboard.md
        - Upload/Download: playwrightActions/fileuploads.md
        - Positive Assertions: playwrightActions/positiveassertions.md
        - Negative Assertions: playwrightActions/negativeassertions.md
        - Alerts: playwrightActions/alerts.md
        - Waits: playwrightActions/waitfor.md
        - Switch: playwrightActions/switch.md
        - Mocking: playwrightActions/fulfill.md
        - Dynamic Objects: playwrightActions/dynamicObject.md
        - General: playwrightActions/general.md
    - Browser Configurations: browsertesting/config.md 
    - Multiple Browser Contexts: browsertesting/multiplebrowsercontexts.md
    - Authentication: browsertesting/playwrightauthenticate.md
    - Webpage Performance: webpageperformance.md
    - Accessibility Testing: accessibility.md
    - Mocking: browsertesting/playwrightmocking.md
 - Mobile App Testing:
    - Premise: mobiletesting/index.md
    - Base Setup: mobiletesting/basesetup.md
    - Android Setup : mobiletesting/androidsetup.md
    - iOS Setup : mobiletesting/iOSsetup.md
    - Appium Inspector : mobiletesting/appiuminspector.md
    - Create Your First Mobile Test: mobiletesting/emulatorsetup.md
    - Actions:
        - Alerts: mobiletesting/mobileActions/alerts.md
        - Dynamic Objects: mobiletesting/mobileActions/dynamicObjects.md
        - General: mobiletesting/mobileActions/general.md
        - Mobile : mobiletesting/mobileActions/mobile.md
        - Positive Assertions : mobiletesting/mobileActions/positiveAssertions.md
        - Negative Assertions : mobiletesting/mobileActions/negativeAssertions.md
        - Scroll: mobiletesting/mobileActions/scroll.md
        - Set: mobiletesting/mobileActions/set.md
        - Store : mobiletesting/mobileActions/store.md
        - Tap : mobiletesting/mobileActions/tap.md
        - Wait: mobiletesting/mobileActions/wait.md
        #- Attribute Assertions: mobiletesting/mobileActions/attributeAssertions.md
        #- Element Assertions: mobiletesting/mobileActions/elementAssertions.md    
        #- Basic: mobiletesting/mobileActions/basic.md 
        #- General: mobiletesting/mobileActions/commonActions.md
 - API Testing:
    - Create Your First API Test: api.md
    - Actions: 
        - General: apiActions/webservice.md
        - Store: apiActions/store.md
        - Assertions: apiActions/assertions.md
 - Message Testing:
    - Premise: messageTesting/index.md
    - JMS (Queues): 
        - Create your first JMS Test: jms/jms.md
        - Queue Actions: jms/queueActions.md
    - Kafka: 
        - Create your first Kafka Test: kafka/kafka.md
        - Kafka Actions: kafka/kafkaActions.md
    - Flat Files: messageTesting/flatfiles.md
 - Database Testing:
    - Premise: databaseTesting/database.md
    - Actions: 
        - General Actions: databaseTesting/dbActions.md
        - Data Storage: databaseTesting/storeActions.md
 - Synthetic Data:
    - Premise: syntheticData/index.md
    - Synthetic Data Generation Actions: 
        - Locale Setup: syntheticData/syntheticDataActions/locale.md
        - Address: syntheticData/syntheticDataActions/address.md
        - Ancient: syntheticData/syntheticDataActions/ancient.md
        - App: syntheticData/syntheticDataActions/app.md
        - Artist: syntheticData/syntheticDataActions/artist.md
        - Avatar: syntheticData/syntheticDataActions/avatar.md
        - Aviation: syntheticData/syntheticDataActions/aviation.md
        - Back to the future: syntheticData/syntheticDataActions/backToTheFuture.md
        - Beer: syntheticData/syntheticDataActions/beer.md
        - Book: syntheticData/syntheticDataActions/book.md
        - Bool: syntheticData/syntheticDataActions/bool.md
        - Business: syntheticData/syntheticDataActions/business.md
        - Cat: syntheticData/syntheticDataActions/cat.md
        - Chunk Norris: syntheticData/syntheticDataActions/chunkNorris.md
        - Code: syntheticData/syntheticDataActions/code.md
        - Color: syntheticData/syntheticDataActions/color.md
        - Commerce: syntheticData/syntheticDataActions/commerce.md
        - Company: syntheticData/syntheticDataActions/company.md
        - Country: syntheticData/syntheticDataActions/country.md
        - Crypto: syntheticData/syntheticDataActions/crypto.md
        - Currency: syntheticData/syntheticDataActions/currency.md
        - Date and Time: syntheticData/syntheticDataActions/dateAndTime.md
        - Demographic: syntheticData/syntheticDataActions/demographic.md
        - Dog: syntheticData/syntheticDataActions/dog.md
        - Dragon Ball: syntheticData/syntheticDataActions/dragonBall.md
        - Educator: syntheticData/syntheticDataActions/educator.md
        - Esports: syntheticData/syntheticDataActions/esports.md
        - File: syntheticData/syntheticDataActions/file.md
        - Finance: syntheticData/syntheticDataActions/finance.md
        - Food: syntheticData/syntheticDataActions/food.md
        - Friends: syntheticData/syntheticDataActions/friends.md
        - Funny Name: syntheticData/syntheticDataActions/funnyName.md
        - Game of Thrones: syntheticData/syntheticDataActions/gameOfThrones.md
        - Hacker: syntheticData/syntheticDataActions/hacker.md
        - Harry Potter: syntheticData/syntheticDataActions/harryPotter.md
        - Hipster: syntheticData/syntheticDataActions/hipster.md
        - Hitch Hikers Guide to the Galaxy: syntheticData/syntheticDataActions/hitchhikersGuideToTheGalaxy.md
        - Hobbit: syntheticData/syntheticDataActions/hobbit.md
        - How I met your mother: syntheticData/syntheticDataActions/howIMetYourMother.md
        - ID Number: syntheticData/syntheticDataActions/idNumber.md
        - Internet: syntheticData/syntheticDataActions/internet.md
        - Job: syntheticData/syntheticDataActions/job.md
        - League of Legends: syntheticData/syntheticDataActions/leagueOfLegends.md
        - Lebowski: syntheticData/syntheticDataActions/lebowski.md
        - Lord of the Rings: syntheticData/syntheticDataActions/lordOfTheRings.md
        - Lorem: syntheticData/syntheticDataActions/lorem.md
        - Matz: syntheticData/syntheticDataActions/matz.md
        - Medical: syntheticData/syntheticDataActions/medical.md
        - Music: syntheticData/syntheticDataActions/music.md
        - Name: syntheticData/syntheticDataActions/name.md
        - Number: syntheticData/syntheticDataActions/number.md
        - Options: syntheticData/syntheticDataActions/options.md
        - Overwatch: syntheticData/syntheticDataActions/overwatch.md
        - Phone Number: syntheticData/syntheticDataActions/phoneNumber.md
        - Pokemon: syntheticData/syntheticDataActions/pokemon.md
        - Random Service: syntheticData/syntheticDataActions/randomService.md
        - Rick and Morty: syntheticData/syntheticDataActions/rickAndMorty.md
        - Robin: syntheticData/syntheticDataActions/robin.md
        - Rock Band: syntheticData/syntheticDataActions/rockBand.md
        - Shakespeare: syntheticData/syntheticDataActions/shakespeare.md
        - Slack Emoji: syntheticData/syntheticDataActions/slackEmoji.md
        - Space: syntheticData/syntheticDataActions/space.md
        - StarTrek: syntheticData/syntheticDataActions/starTrek.md
        - Stock: syntheticData/syntheticDataActions/stock.md
        - Super Hero: syntheticData/syntheticDataActions/superHero.md
        - Team: syntheticData/syntheticDataActions/team.md
        - Twin Peaks: syntheticData/syntheticDataActions/twinPeaks.md
        - University: syntheticData/syntheticDataActions/university.md
        - Weather: syntheticData/syntheticDataActions/weather.md
        - Witcher: syntheticData/syntheticDataActions/witcher.md
        - Yoda: syntheticData/syntheticDataActions/yoda.md
        - Zelda: syntheticData/syntheticDataActions/zelda.md
        - Miscellaneous: syntheticData/syntheticDataActions/misc.md
 - Customizations:
    - Full flexibility: customizations/index.md
    - Engine: customizations/engine.md
    - Custom functions: customizations/customfunction.md
    - Command Line Interface: cli.md            
 - Integrations :
    - BDD: bdd.md
    - Azure DevOps Test Plan: testplan.md
    - Continuous Integration: 
        - Getting Started: integrations/ci.md 
        - Azure DevOps: integrations/azuredevops.md
        - GitHub Actions: integrations/githubactions.md
        - Circle CI: integrations/circleci.md      
 - Hidden Gems :
    - Reporting: browsertesting/playwrightreporting.md
    - Shortcuts: shortcuts.md
    - Additional features: additionalfeatures.md
    - String Operations: stringOperations.md
    - Global Datasheets: globalDataSheet.md
    - Tips: tips.md
    - Troubleshooting: troubleshooting.md 
         
extra:
  footer:
     - text: |
           hellooooooooo
      


extra_css:
  - ing.css

copyright: Created and maintained by ING INGenious Team 

features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.footnote.tooltips
    - content.action.edit
extra:
  generator: false  

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      pygments_style: default
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html   
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys   
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true

repo_url: https://github.com/ing-bank/INGenious